[package]
name = "mini-redis"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
tokio = { git = "https://github.com/tokio-rs/tokio", features = ["full"] }

atoi = "0.3.2"
